# Generated by Django 5.1.7 on 2025-07-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
    ]
