# Generated by Django 5.1.7 on 2025-07-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name_of_company', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=10)),
                ('date_of_listing', models.DateField()),
                ('paid_up_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isin_number', models.CharField(max_length=12, unique=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sme_stocks', to='rooms.room')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'room'], name='rooms_smest_symbol_b9db1e_idx'), models.Index(fields=['isin_number'], name='rooms_smest_isin_nu_173bb5_idx')],
                'unique_together': {('room', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name_of_company', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=10)),
                ('date_of_listing', models.DateField()),
                ('paid_up_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isin_number', models.CharField(max_length=12, unique=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='rooms.room')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'room'], name='rooms_stock_symbol_ab61a4_idx'), models.Index(fields=['isin_number'], name='rooms_stock_isin_nu_6f8668_idx')],
                'unique_together': {('room', 'symbol')},
            },
        ),
    ]
