# Generated by Django 5.1.7 on 2025-07-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_smestock_stock'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smestock',
            name='rooms_smest_symbol_b9db1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='rooms_stock_symbol_ab61a4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='smestock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='smestock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='smestock',
            index=models.Index(fields=['symbol'], name='rooms_smest_symbol_fe0996_idx'),
        ),
        migrations.AddIndex(
            model_name='smestock',
            index=models.Index(fields=['name_of_company'], name='rooms_smest_name_of_f0d70b_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='rooms_stock_symbol_2a9edd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['name_of_company'], name='rooms_stock_name_of_cdab09_idx'),
        ),
        migrations.RemoveField(
            model_name='smestock',
            name='room',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='room',
        ),
    ]
