# Generated by Django 5.1.7 on 2025-07-20 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_smestock_rooms_smest_symbol_b9db1e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('order_category', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP_LOSS', 'Stop Loss Order')], default='MARKET', max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('filled_quantity', models.PositiveIntegerField(default=0)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_FILLED', 'Partially Filled')], default='PENDING', max_length=20)),
                ('order_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_timestamp', models.DateTimeField(blank=True, null=True)),
                ('cancellation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('total_buy_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_sell_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('total_quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('average_buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_buy_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_sell_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userbalance',
            old_name='cash_balance',
            new_name='total_cash_balance',
        ),
        migrations.AddField(
            model_name='trade',
            name='execution_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='market_price_at_execution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='reserved_cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together={('user', 'room')},
        ),
        migrations.AddIndex(
            model_name='userbalance',
            index=models.Index(fields=['user', 'room'], name='rooms_userb_user_id_76b085_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol'], name='rooms_marke_symbol_44b3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['last_updated'], name='rooms_marke_last_up_0bfd02_idx'),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='rooms.orderbook'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'room'], name='rooms_trade_user_id_d7909d_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'room'], name='rooms_trade_symbol_b832cd_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['timestamp'], name='rooms_trade_timesta_26f3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['execution_id'], name='rooms_trade_executi_2cf4f0_idx'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['user', 'room'], name='rooms_order_user_id_d03bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['symbol', 'room'], name='rooms_order_symbol_4716fd_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['order_status'], name='rooms_order_order_s_f73091_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['order_timestamp'], name='rooms_order_order_t_a0a927_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsession',
            index=models.Index(fields=['user', 'room'], name='rooms_tradi_user_id_0c14f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsession',
            index=models.Index(fields=['session_start'], name='rooms_tradi_session_31ec7a_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['user', 'room'], name='rooms_userp_user_id_de4255_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['symbol'], name='rooms_userp_symbol_774770_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userportfolio',
            unique_together={('user', 'room', 'symbol')},
        ),
    ]
